config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :flights, only: [:create, :show]
  resources :airlines, only: [:show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts, only: [:index, :create, :destroy]

  root 'posts#index'

  match '/signup', to: 'users#new', via: 'get'
  match '/login', to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'

end

app/models/airline.rb
class Airline < ActiveRecord::Base
	has_many :flights
	has_many :posts, through: :flights

	validates :name, presence: true

	def satisfied_percent
		posts = []
		self.flights.each {|flight| posts << flight.posts }
		total = posts.flatten.count
		satisfied = posts.select{|post| post.satisfied}
		satisfied.length/total.to_f * 100
	end

	def parse_flights
		parsed_flights = self.flights.map do |flight|
			{
				"flight" => flight.fs_code.to_s,
				"flight_number" => flight.flight_number,
				"arrivalDifference" => arrival_difference(flight),
				"departureDifference" => departure_difference(flight),
				"arrivalActual" => flight.time_to_s(flight.arrival_actual),
				"departureActual" => flight.time_to_s(flight.departure_actual)
			}
		end
		parsed_flights.to_json
	end

	def difference_to_s(time)
		minutes = (time/60).to_i.to_s
	end

	def arrival_difference(flight)
		difference_to_s(flight.arrival_scheduled - flight.arrival_actual)
	end

	def departure_difference(flight)
		difference_to_s(flight.departure_scheduled - flight.departure_actual)
	end

	def time_to_s(time)
		time.strftime("%I:%M %p")
	end

	def satisfied_percent
		total = self.posts.count
		satisfied = self.posts.select{|post| post.satisfied}
		(satisfied.length/total.to_f * 100).to_i
	end

end

app/models/airport.rb
class Airport < ActiveRecord::Base
  has_many :departing_flights
  has_many :arriving_flights
end

app/models/flight.rb
class Flight < ActiveRecord::Base
	FLIGHT_QUERY_URL_START = "https://api.flightstats.com/flex/flightstatus/rest/v2/json/route/status"
	CREDENTIALS = "?appId=#{ENV['FS_ID']}&appKey=#{ENV['FS_KEY']}"
	FLIGHT_QUERY_URL_END = "&hourOfDay=0&numHours=24&utc=false"

	# before_create :check_time
	belongs_to :airline
	belongs_to :departure_airport, class_name: 'Airport'
	belongs_to :arrival_airport, class_name: 'Airport'
	has_many :posts

	validates :airline, presence: true
	validates :departure_scheduled, presence: true
	validates :departure_actual, presence: true
	validates :arrival_scheduled, presence: true
	validates :arrival_actual, presence: true
	validates :departure_airport, presence: true
	validates :arrival_airport, presence: true

	validate :depart_cant_be_arrival

	def depart_cant_be_arrival
		if arrival_airport == departure_airport
			errors.add(:arrival_airport, "can't be in same city as departure airport")
		end
	end

	def time_to_s(time)
		time.strftime("%I:%M %p")
	end

	def difference_to_s(time)
		on_time = time < 0 ? 'Early by ' : 'Delayed by '
		hours = (time.abs / 3600).to_i
		minutes = ((time.abs/60) - (hours * 60)).to_i
		on_time + "#{hours} hour(s) and #{minutes} minute(s)"
	end

	def satisfied_percent
		total = self.posts.count
		satisfied = self.posts.select{|post| post.satisfied}
		(satisfied.length/total.to_f * 100).to_i
	end

	def arrival_difference
		difference_to_s(self.arrival_actual - self.arrival_scheduled)
	end

	def departure_difference
		difference_to_s(self.departure_actual - self.departure_scheduled)
	end

	def self.api_query(args)
	  url = FLIGHT_QUERY_URL_START + "/#{args[:departing]}/#{args[:arriving]}/arr/#{args[:year]}/#{args[:month]}/#{args[:day]}" + CREDENTIALS + FLIGHT_QUERY_URL_END
	  resp = Net::HTTP.get_response(URI.parse(url))
	  data = resp.body
	  result = JSON.parse(data)
	  if result.has_key? 'Error'
	     raise "web service error"
	  end
	  return result
	end

	def self.parse_flights(api_result)

		landed_flights = api_result['flightStatuses'].select do |flight|
			flight['operationalTimes']['actualGateArrival']
		end

		selectable_flights = []

		landed_flights.each do |flight|
			new_flight = Flight.find_by(fs_code: flight['flightId'])
			unless new_flight
				new_flight = Flight.new

				new_flight.departure_airport = Airport.find_by(fs_code: flight['departureAirportFsCode'])
				new_flight.arrival_airport = Airport.find_by(fs_code: flight['arrivalAirportFsCode'])
				new_flight.airline = Airline.find_by(fs_code: flight['carrierFsCode'])

				new_flight.arrival_scheduled = flight['operationalTimes']['scheduledGateArrival']['dateLocal']
				new_flight.arrival_actual = flight['operationalTimes']['actualGateArrival']['dateLocal']
				new_flight.departure_scheduled = flight['operationalTimes']['scheduledGateDeparture']['dateLocal']
				new_flight.departure_actual = flight['operationalTimes']['actualGateDeparture']['dateLocal']
				new_flight.fs_code = flight['flightId']
				new_flight.flight_number = flight['flightNumber']
				new_flight.save
			end
			selectable_flights << new_flight
		end
		return selectable_flights
	end

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :flight, :user, :text, :satisfied, presence: :true
  validates :text, length: { maximum: 140}
  belongs_to :user
  belongs_to :flight
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  validates :username, :password, :password_confirmation, :email, presence: :true
  validates :email, uniqueness: { case_sensitive: false }, format: {with: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i, message: "Invalid email format"}
  validates :password, length: { minimum: 5 }

  has_secure_password
end

app/controllers/airlines_controller.rb
class AirlinesController < ApplicationController

	def show
		current_user
		@airline = Airline.find(params[:id])
		@flights = @airline.parse_flights
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/flights_controller.rb
require 'json'
require 'net/http'
require 'date'

class FlightsController < ApplicationController

	respond_to :json

	def create
		split_date = params[:date].split("-")
		date_hash = {year: split_date[0], month: split_date[1], day: split_date[2]}
		result = Flight.api_query(params.merge(date_hash))
		@post = Post.new
		@flights = Flight.parse_flights(result)
		@flights.map!{|flight| create_option(flight)}
		@flights.sort!
		render 'posts/_create_post_form', layout: false
	end

	def show
		@flight = Flight.find(params[:id])
		@posts = @flight.posts.all.reverse
	end

	private

		def create_option(flight)
			["#{flight.airline.name} Flight #{flight.flight_number} (Arrived #{time_to_s(flight.arrival_actual)})", flight.id]
		end

		def time_to_s(time)
			time.strftime("%I:%M %p")
		end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
    current_user
    @posts = Post.all.reverse
	end

  def create
    @post = Post.new(post_params)
    @post.flight = Flight.find(params[:post][:flight])
    @post.user = current_user
    @post.save
    redirect_to posts_path
  end

  def destroy
  end

  private

  def post_params
    params.require(:post).permit(:text, :satisfied)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		if current_user
			redirect_to(root_path)
		else
			render 'new'
		end
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			session[:current_user_id] = user.id
			redirect_to root_path
		else
			redirect_to root_path
		end
	end

	def destroy
		session.clear
		redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		current_user
		@users = User.all
	end

	def new
		if current_user
			redirect_to(root_path)
		else
			@user = User.new
			render 'new'
		end
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:current_user_id] = @user.id
			redirect_to root_path
		else
			render 'new'
		end
	end

	def show
		current_user
		unless User.exists?(id: params[:id])
			redirect_to root_path
		else 
			@user = User.find(params[:id])
			@posts = @user.posts.reverse
		end
	end

	private

	   def user_params
     	params.require(:user).permit(:username, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def current_user=(user)
		@current_user = user
	end

  def current_user
    if session[:current_user_id]
      @current_user ||= User.find(session[:current_user_id])
    end
  end

end

app/views/airlines/show.html.erb
<h1><%= @airline.name %></h1>
<div class="small-10 columns">
  <div class="row">
    <div class="small-1 columns text-right">
      <i class="fi-dislike"></i>
    </div>
    <div class="small-10 columns">
      <div class="progress small-12">
        <span class="meter text-center" style="width: <%= @airline.satisfied_percent %>%"></span>
      </div>
    </div>
    <div class="small-1 columns">
      <i class="fi-like"></i>
    </div>
  </div>
</div>
<%= render partial: 'layouts/statistics' %>
<div id="hidden_flights" style="display: none">
	<%= @flights %>
</div>

app/views/flights/show.html.erb
<div class="small-10 columns small-centered">
  <div class="row">
    <h1><%= link_to "#{@flight.airline.name}", airline_path(@flight.airline.id) %><%=' Flight ' + @flight.flight_number %></h1>
    <h4><%= @flight.departure_airport.name %> (<%= @flight.departure_airport.fs_code %>) to <%= @flight.arrival_airport.name %> (<%= @flight.arrival_airport.fs_code %>)</h4>
    <div class="small-10 columns">
      <div class="row">
        <div class="small-1 columns text-right">
          <i class="fi-dislike"></i>
        </div>
        <div class="small-10 columns">
          <div class="progress small-12">
            <span class="meter text-center" style="width: <%= @flight.satisfied_percent %>%"></span>
          </div>
        </div>
        <div class="small-1 columns">
          <i class="fi-like"></i>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="small-12 columns">Departed <%= @flight.time_to_s(@flight.departure_actual) %></div>
    </div>
    <div class="row">
      <div class="small-12 columns">Arrived <%= @flight.time_to_s(@flight.arrival_actual) %></div>
    </div>
    <div class="row">
      <div class="small-12 columns"><%= @flight.arrival_difference %></div>
    </div>
    <hr>
  </div>
</div>

<%= render partial: 'layouts/fleet', locals: {posts: @posts} %>

app/views/layouts/_fleet.html.erb
<div class="small-10 columns small-centered">
  <div class="row">
    <ul class="small-block-grid-1 medium-block-grid-2 large-block-grid-3">
      <% posts.each do |post| %>
        <li><div class="panel fleet">
        	<%= link_to "#{post.user.username}", user_path(post.user.id) %>
          <% if post.satisfied %>
            <i class="fi-like"></i>
          <% else %>
            <i class="fi-dislike"></i>
          <% end %><br>
        	<%=post.text%><br>
          <%= link_to "#{post.flight.airline.name} Flight #{post.flight.flight_number}", flight_path(post.flight.id) %>
        </div></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_nav_bar.html.erb
<nav class="top-bar" data-topbar>
	<ul class="title-area">	
		<li class="name">
			<h1><a href="/">Flitter</a></h1>
		 </li>
	 </ul>
	 <section class="top-bar-section">
		<!-- Right Nav Section -->
		<ul class="right">
			<% if @current_user %>
				<li><%= link_to 'My Account', user_path(@current_user.id) %></li>
				<li><%= link_to 'Log Out', logout_path, method: "DELETE" %></li>
			<% else %>
				<li><%= link_to 'Sign Up', new_user_path %></li>
				<li><%= link_to 'Log In', login_path %></li>
			<% end %>
		</ul>
	 </section>
</nav>

app/views/layouts/_statistics.html.erb
<div class="row">
  <div class ="description">
            <table>
          <tr>
            <td>
              <select>
                <option id="item" value="arrival">Arrival Times</option>
                <option id="item" value="departure">Departure Times</option>
              </select>
            </td>
        </tr>
        <tr>
              <td>
                <ul>
                  <li><input type="checkbox" class="checkbox" name="check" value="sort"> </li>
                  <li>Sort by earliest to latest</li>
                </ul>
              </div>
            </td>

        </tr>
          </table>
      </div>
      <br>
      <div id="chart-container"></div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="">
    <meta name="author" content="">

    <title><%= content_for?(:title) ? yield(:title) : "Flitter" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render partial: "/layouts/nav_bar" %>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/posts/_create_post_form.html.erb
<div class="small-10 columns small-centered">
  <div class="row signup">
    
    <%= form_for @post, url: posts_path do |f| %>
      
      <%= f.select :flight, @flights %><br>
      <%= f.text_area :text, placeholder: "Write a post here", maxlength: '140', rows: '3' %><br>
      
      <%= label_tag(:satisfied, "Were you satisfied?") %>

	  	<input id = "satisfied" type = "radio" name = "post[satisfied]" value = true>
		    <label for = "satisfied">
		  		<img src="https://scontent-a.xx.fbcdn.net/hphotos-xpa1/t1.0-9/10462602_2612795282415_601726830170641479_n.jpg">
		  	</label>

	  	<input id = "not_satisfied" type = "radio" name = "post[satisfied]" value = false>
		  	<label for = "not_satisfied">
		  		<img src="https://fbcdn-sphotos-a-a.akamaihd.net/hphotos-ak-xfa1/t1.0-9/10553588_2612795322416_1835318099286727678_n.jpg">
		  	</label>
      
     
      <%= f.submit "Flit It!", class: 'button'%> 
      
    <% end %>
  </div>
  <hr>
</div>

app/views/posts/_flight_query_form.html.erb
<div class="small-10 columns small-centered">
  <div class="row signup">
    <%= form_tag flights_path, id: "flight_api_form" do %>
      
      <%= label_tag (:departing), "Enter your departing airport:" %>
      <%= text_field_tag (:departing) %><br>
      
      <%= label_tag (:arriving), "Enter your arriving airport:" %>
      <%= text_field_tag (:arriving) %><br>
      
      <%= date_field_tag (:date) %><br>
      
      <%= submit_tag "Flind It!", class: 'button' %> 
      
    <% end %>
  </div>
  <hr>
</div>

app/views/posts/index.html.erb
<div class="small-10 columns small-centered">
  <div class="row">
    <center>
      <h1> Welcome to Flitter! </h1>
    </center> 
  </div>
</div>

<% if @current_user %>
	<div id="post-form">
	</div>

	<div id="query-form">
		<%= render partial: 'flight_query_form' %>
	</div>
<% end %>

<%= render partial: 'layouts/fleet', locals: {posts: @posts} %>

app/views/users/index.html.erb
<h1> Users page</h1>
<h2> <% @users.each do |user| %></h2>
<ul> 
	<li> <%= user.username %> </li>
</ul>
<% end %>

app/views/users/new.html.erb
<div class="small-10 columns small-centered">
	<div class="row signup">
		<h1>Sign Up</h1>
		<%= form_for(@user) do |f| %>
			<label for="left-label" class="left"><%= f.label :username %> </label>
			<%= f.text_field :username %>
			<label for="left-label" class="left"><%= f.label :email %> </label>
			<%= f.text_field :email %>
			<label for="left-label" class="left"><%= f.label :password %> </label>
			<%= f.password_field :password %>
			<label for="left-label" class="left"><%= f.label :password_confirmation %> </label>
			<%= f.password_field :password_confirmation %>
			<%= f.submit "Sign Up", class: 'button' %>
		<% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>Here are all of the flits for <%= @user.username %></h1>
<%= render partial: 'layouts/fleet', locals: {posts: @posts} %>